### ISSUE TITLE
generate documentation

### ISSUE THREAD

**Issue by prakashupes** [prakashupes/pgrouting#7]

**Comment by cvvergara** [comment]
```
make doc
```

**Comment by prakashupes** [comment]
make: Nothing to be done for 'doc'.

**Comment by prakashupes** [comment]
Should I run it from build directory??

**Comment by cvvergara** [comment]
yes please

**Comment by prakashupes** [comment]
```
-- CMAKE_BUILD_TYPE Debug
-- DOXYGEN_MINIMUM_VERSION=1.7
-- SPHINX_MINIMUM_VERSION=1.1
-- POSTGRESQL_MINIMUM_VERSION=9.2.0
-- POSTGIS_MINIMUM_VERSION=2.0.0
-- GNU_CXX_MINIMUM_VERSION=4.6
-- CLANG_CXX_MINIMUM_VERSION=
-- MSVC_CXX_MINIMUM_VERSION=18.0
-- dir='/home/prakash/Github/pgrouting/cmake'
-- Using  -std=c++11.
-- POSTGRESQL_PG_CONFIG is /usr/bin/pg_config
-- POSTGRESQL_EXECUTABLE is /usr/lib/postgresql/10/bin/postgres
-- POSTGRESQL_VERSION_STRING in FindPostgreSQL.cmake is PostgreSQL 10.11 (Ubuntu 10.11-1.pgdg18.04+1)
-- POSTGRESQL_INCLUDE_DIR: /usr/include/postgresql/10/server
-- POSTGRESQL_LIBRARIES: /usr/lib/x86_64-linux-gnu
-- PGSQL_VERSION=1011
-- Boost headers were found here: /usr/include
-- Boost VERSION 1.65.1
-- BOOST_VERSION_OK 1
-- BOOST_Geometry_VERSION_OK 1
-- Developers documentation.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) (Required is at least version "1.7")
-- PGROUTING_DOC_TARGETS = html
-- PGROUTING_BUILD_LANGUAGES = en
-- SPHINXINTL_LANGUAGE = en
-- Checking for package 'Sphinx'
-- SPHINX_VERSION Sphinx (sphinx-build) 1.6.7
-- SPHINX_VERSION 1.6.7
-- PGR_DOCUMENTATION_BUILD_DIR = /home/prakash/Github/pgrouting/build/doc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/prakash/Github/pgrouting/build
Scanning dependencies of target html-en
Generating html/en documentation ...
Running Sphinx v1.6.7
making output directory...

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 163, in __init__
    raise ConfigError(CONFIG_ERROR % traceback.format_exc())
ConfigError: There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/usr/lib/python2.7/dist-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 15, in <module>
    import sphinx_bootstrap_theme
ImportError: No module named sphinx_bootstrap_theme


Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/usr/lib/python2.7/dist-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 15, in <module>
    import sphinx_bootstrap_theme
ImportError: No module named sphinx_bootstrap_theme

doc/CMakeFiles/html-en.dir/build.make:266: recipe for target 'doc/CMakeFiles/html-en' failed
make[3]: *** [doc/CMakeFiles/html-en] Error 1
CMakeFiles/Makefile2:3561: recipe for target 'doc/CMakeFiles/html-en.dir/all' failed
make[2]: *** [doc/CMakeFiles/html-en.dir/all] Error 2
CMakeFiles/Makefile2:3541: recipe for target 'doc/CMakeFiles/doc.dir/rule' failed
make[1]: *** [doc/CMakeFiles/doc.dir/rule] Error 2
Makefile:580: recipe for target 'doc' failed
make: *** [doc] Error 2
```

**Comment by cvvergara** [comment]
> No module named sphinx_bootstrap_theme

```
pip install sphinx_bootstrap_theme
```

**Comment by prakashupes** [comment]
done

**Comment by prakashupes** [comment]
```
WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting
generating indices... genindex
writing additional pages... search
copying images... [  6%] images/Fig1-originalData.png
copying images... [ 12%] images/after_node_net.png
copying images... [ 18%] images/Fig6-undirected.png
copying images... [ 25%] images/undirected_sampledata_c.png
copying images... [ 31%] images/rightDrivingSide.png
copying images... [ 37%] images/boost-inside.jpeg
copying images... [ 43%] images/leftDrivingSide.png
copying images... [ 50%] images/transformation.png
copying images... [ 56%] images/undirected_sampledata_a.png
copying images... [ 62%] _static/images/ccbysa.png
copying images... [ 68%] images/undirected_sampledata_b.png
copying images... [ 75%] images/original.png
copying images... [ 81%] images/noMatterDrivingSide.png
copying images... [ 87%] images/Fig2-cost.png
copying images... [ 93%] images/before_node_net.png
copying images... [100%] images/Fig4-costUndirected.png

copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.
Built target html-en
Scanning dependencies of target html
Built target html
Scanning dependencies of target doc
Built target doc

**Comment by cvvergara** [comment]
you can close
